### ISSUE TITLE
Error during setup of component wiim_custom

### ISSUE THREAD

**Issue by rosentrieb** [onlyoneme/home-assistant-custom-components-wiim#19]
Logger: homeassistant.setup
Quelle: setup.py:404
Erstmals aufgetreten: 19:02:34 (1 Vorkommnisse)
Zuletzt protokolliert: 19:02:34

Error during setup of component wiim_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiim_custom/__init__.py", line 82, in setup
    hass.services.async_register(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2522, in async_register
    self._hass.verify_event_loop_thread("async_register")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'wiim_custom' calls async_register from a thread at custom_components/wiim_custom/__init__.py, line 82: hass.services.async_register(. Please report it to the author of the 'wiim_custom' custom integration.

**Comment by fredR142** [comment]
just to confirm this is not a single user issue as i have the same !

**Comment by jpsingh10** [comment]
The latest HA update broke the integration, I reverted back to the previous version of HA and it started working again.

**Comment by dablanco83** [comment]
Yes same here

**Comment by jiruss** [comment]
+1

**Comment by onlyoneme** [comment]
Should be ok now, please use the latest beta branch code.

**Comment by rosentrieb** [comment]
Thanks for your quick update!

**Comment by alexleekt** [comment]
can you tag it so HACS picks it up? :)

**Comment by Github-Axel** [comment]
Indeed, same problem with HA 2024.5.2.
Problem solved with the beta version !

Thank you a lot to maintain this great addon.

**Comment by shampeon** [comment]
HACS 1.34.0 still isn't showing an updated beta in 2024.5.2. As @alexleekt says, you need to retag the beta so HACS shows the update.

**Comment by CodeCommander** [comment]
How can we go about using the beta version while we wait for the tag to be added? I had previously installed from HACS.

**Comment by Mart11** [comment]
Hi, thx for your work! When can we expect a new version release with this fix included?

**Comment by CodeCommander** [comment]
I figured out how to use the beta branch for people that might not know:

1. Go to the HACS tab, and find the WiiM Decices.
2. Tap on it and then tap on the … in the top right.
3. Choose “Redownload”, enabled Beta versions. Wait a bit for it to load, pick the beta you want, wait for it to load and then click download.
4. Restart your Home Assistant

**Comment by jaid33** [comment]
> I figured out how to use the beta branch for people that might not know:
> 
>     1. Go to the HACS tab, and find the WiiM Decices.
> 
>     2. Tap on it and then tap on the … in the top right.
> 
>     3. Choose “Redownload”, enabled Beta versions. Wait a bit for it to load, pick the beta you want, wait for it to load and then click download.
> 
>     4. Restart your Home Assistant

Are you sure this will download the fixed version?
The version with "0.3.6-beta"-tag is 1 year old and the new fixed version (with "2024.5.0 async setup"-comment seems to have no tag.

**Comment by Ehcoboy** [comment]
I tried with beta version still not working

**Comment by shampeon** [comment]
Correct, there's no way, at this time, to get the corrected version from the UI. You can try [this workaround](https://github.com/onlyoneme/home-assistant-custom-components-wiim/issues/18#issuecomment-2119363994) in the meantime.

**Comment by Ehcoboy** [comment]
Thanks mate! I found the mentioned workaround  it's working it working like a charm now
